import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import RaidenNavbar from "../../components/Navbar";
import { ToastProvider } from "../contexts/toastContext";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raiden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <Toaster />

          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
