import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ToastProvider } from "../contexts/toastContext";
import { Toaster } from "sonner";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raiden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <div className="flex">
            <Sidebar />

            <div className="pl-48">{children}</div>
          </div>
        </ToastProvider>

        <Toaster />
      </body>
    </html>
  );
}
